version: '4.32'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - "3308:3306"
    volumes:
       - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
   mysql_data: